name: 🎧 Mood Markdown Music Commit

on:
  workflow_dispatch:
    inputs:
      mood:
        description: "Pick your mood of the day"
        required: true
        default: "😎 chillin"
        type: choice
        options:
          - 😎 chillin
          - 🔥 motivated
          - 🤯 overwhelmed
          - 😭 sad boi hours
          - 🧘‍♂️ zen mode
          - 🥱 sleepy af
          - 😤 grinding
          - 🤖 robot mode
          - 🥳 feeling myself
      note:
        description: "Write your vibe or story for the day"
        required: false
        default: ""

jobs:
  mood_commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v4

      - name: ⚙️ Set up Git
        run: |
          git config --global user.name "Bennnnip"
          git config --global user.email "vissarut_prom@example.com"
                - name: 🎧 Write mood + music to .md
        run: |
          echo '#!/bin/bash' > write_mood.sh
          echo 'MOOD="${{ github.event.inputs.mood }}"' >> write_mood.sh
          echo 'NOTE="${{ github.event.inputs.note }}"' >> write_mood.sh
          echo 'TIMESTAMP=$(date -u +"%Y-%m-%d")' >> write_mood.sh
          echo 'DATETIME_FULL=$(date -u)' >> write_mood.sh
          - echo 'cat << EOF > write_mood.sh
#!/bin/bash
declare -A MUSIC
MUSIC["😎 chillin"]="https://music.apple.com/us/album/chihiro/1732431344?i=1732431353"
MUSIC["🔥 motivated"]="https://music.apple.com/us/album/new-normal/1576256376?i=1576256623"
MUSIC["🤯 overwhelmed"]="https://music.apple.com/us/album/i-can-die-now/1735241727?i=1735241734"
MUSIC["😭 sad boi hours"]="https://music.apple.com/us/album/vasopressin/1733689891?i=1733689892"
MUSIC["🧘‍♂️ zen mode"]="https://music.apple.com/us/album/die-with-a-smile/1580118092?i=1580118094"
MUSIC["🥱 sleepy af"]="https://music.apple.com/us/album/wake-me-up/1709437960?i=1709437963"
MUSIC["😤 grinding"]="https://music.apple.com/us/album/gravity/1450646638?i=1450646646"
MUSIC["🤖 robot mode"]="https://music.apple.com/us/album/superposition/1448216613?i=1448216622"
MUSIC["🥳 feeling myself"]="https://music.apple.com/us/album/lust-for-life-feat-the-weeknd/1440905176?i=1440905176"

TRACK=\${MUSIC["\$MOOD"]}
echo "🎧 Mood: \$MOOD"
echo "🔗 Track: \$TRACK"
EOF' >> write_mood.sh
          
           'echo "" >> .mood-log.md' >> write_mood.sh 
           'echo "---" >> .mood-log.md' >> write_mood.sh
           'echo "" >> .mood-log.md' >> write_mood.sh

          bash write_mood.sh

          bash write_mood.sh

      - name: 📊 Generate Mood Summary
        run: |
          awk '/^# 🧠 Mood Entry/ {entry++}
               /^(\*\*Mood\*\*:)/ {
                 mood = $2;
                 gsub(/\*\*/, "", mood);
                 counts[mood]++;
               }
               END {
                 print "## 📊 Mood Stats (Auto Summary)\n";
                 printf "| Mood               | Count |\n";
                 printf "|--------------------|-------|\n";
                 total = 0;
                 for (m in counts) {
                   printf "| %-18s | %5d |\n", m, counts[m];
                   total += counts[m];
                 }
                 printf "\n_Total Entries: %d_\n\n---\n", total;
               }' .mood-log.md > .mood-stats.md

          # Remove old stats block if exists
          awk '/^## 📊 Mood Stats/,/^---/{next} {print}' .mood-log.md > .mood-log-clean.md
          cat .mood-log-clean.md .mood-stats.md > .mood-log.md
          rm .mood-log-clean.md .mood-stats.md

          COMMIT_MSG="🌈 Mood Check-in: ${{ github.event.inputs.mood }}"
          if [ -n "${{ github.event.inputs.note }}" ]; then
            COMMIT_MSG="$COMMIT_MSG — ${{ github.event.inputs.note }}"
          fi
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - name: ✅ Commit & Push
        run: |
          git add .mood-log.md
          if git diff --cached --quiet; then
            echo "🛑 No changes to commit."
          else
            git commit -m "$COMMIT_MSG"
            git push
