name: 🎧 Mood Markdown Music Commit

on:
  workflow_dispatch:
    inputs:
      mood:
        description: "Pick your mood of the day"
        required: true
        default: "😎 chillin"
        type: choice
        options:
          - 😎 chillin
          - 🔥 motivated
          - 🤯 overwhelmed
          - 😭 sad boi hours
          - 🧘‍♂️ zen mode
          - 🥱 sleepy af
          - 😤 grinding
          - 🤖 robot mode
          - 🥳 feeling myself
      note:
        description: "Write your vibe or story for the day"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  mood_commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v4

      - name: ⚙️ Set up Git
        run: |
          git config --global user.name "Bennnnip"
          git config --global user.email "vissarut.prom@gmail.com"

      - name: 🎧 Write mood + music to .md
        run: |
         echo '#!/bin/bash' > write_mood.sh
         echo 'MOOD="${{ github.event.inputs.mood }}"' >> write_mood.sh
         echo 'NOTE="${{ github.event.inputs.note }}"' >> write_mood.sh
         echo 'TIMESTAMP=$(date -u +"%Y-%m-%d")' >> write_mood.sh
    
         echo 'declare -A MUSIC' >> write_mood.sh
         # ... (your MUSIC array here)
    
         echo 'TRACK=${MUSIC[$MOOD]}' >> write_mood.sh
         echo 'echo "🧠 Mood Entry — $TIMESTAMP" >> .mood-log.md' >> write_mood.sh
         echo 'echo "**Mood**: $MOOD" >> .mood-log.md' >> write_mood.sh
         echo 'echo "**Note**: $NOTE" >> .mood-log.md' >> write_mood.sh
         echo 'echo "**Track**: [Link]($TRACK)" >> .mood-log.md' >> write_mood.sh
         echo 'echo "" >> .mood-log.md' >> write_mood.sh
         echo 'echo "---" >> .mood-log.md' >> write_mood.sh
         echo 'echo "" >> .mood-log.md' >> write_mood.sh
        
         bash write_mood.sh

      - name: 📊 Generate Mood Summary
        run: |
          awk '
          BEGIN {
            print "## 📊 Mood Stats (Auto Summary)\n";
            printf "| Mood               | Count |\n";
            printf "|--------------------|-------|\n";
          }
          /^\*\*Mood\*\*: / {
            sub(/\*\*Mood\*\*: /, "", $0);
            counts[$0]++;
          }
          END {
            total = 0;
            for (mood in counts) {
              printf "| %-18s | %5d |\n", mood, counts[mood];
              total += counts[mood];
            }
            printf "\n_Total Entries: %d_\n\n---\n", total;
          }' .mood-log.md > .mood-stats.md

          awk '/^## 📊 Mood Stats/,/^---/{next} {print}' .mood-log.md > .mood-log-clean.md
          cat .mood-log-clean.md .mood-stats.md > .mood-log.md
          rm .mood-log-clean.md .mood-stats.md

      - name: 🐍 Set up Python
        run: |
          python3 -m pip install --upgrade pip
          pip install matplotlib

      - name: 📊 Generate Pie Chart
        run: |
          echo "
          import matplotlib.pyplot as plt 
          from collections import Counter
          import re
          import os
          os.makedirs('assets', exist_ok=True)
          with open('.mood-log.md', 'r') as f:
            lines = f.readlines()
            
            moods = [re.search(r'\*\*Mood\*\*: (.*?)\\n?', line).group(1) for line in lines if '**Mood**:' in line]
            counts = Counter(moods)
            labels = list(counts.keys())
            sizes = list(counts.values())
            colors = plt.cm.Paired(range(len(labels)))
            plt.figure(figsize=(6,6))
            plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140)
            plt.title('Mood Breakdown')
            plt.axis('equal')
            plt.tight_layout()
            plt.savefig('assets/mood-chart.png', dpi=200)
            " > chart.py
               python3 chart.py

      - name: 🖼️ Insert Mood Chart into Markdown
        run: |
          awk '!/\!\[Mood Chart\]\(assets\/mood-chart\.png\)/' .mood-log.md > .temp-log.md
          echo -e "\n![Mood Chart](assets/mood-chart.png)\n" >> .temp-log.md
          mv .temp-log.md .mood-log.md

      - name: ✅ Commit & Push
        run: |
          git add .mood-log.md
          git add assets/mood-chart.png
      
          COMMIT_MSG="🌈 Mood Check-in: ${{ github.event.inputs.mood }}"
          NOTE="${{ github.event.inputs.note }}"
      
          if [ -n "$NOTE" ]; then
            COMMIT_MSG="$COMMIT_MSG — $NOTE"
          fi
      
          if git diff --cached --quiet; then
            echo "🛑 No changes to commit."
          else
            git commit -m "$COMMIT_MSG"
            git push
          fi
      
           
